apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: osk-cp-sr-test-1
  namespace: kafka
  labels:
    strimzi.io/cluster: osk-kraft
spec:
  partitions: 3
  replicas: 3
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: osk-cp-sr-test-2
  namespace: kafka
  labels:
    strimzi.io/cluster: osk-kraft
spec:
  partitions: 3
  replicas: 3
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: osk-cp-sr-test-3
  namespace: zookeeper
  labels:
    strimzi.io/cluster: osk-non-kraft
spec:
  partitions: 3
  replicas: 3
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: osk-cp-sr-test-5
  namespace: zookeeper
  labels:
    strimzi.io/cluster: osk-non-kraft
spec:
  partitions: 3
  replicas: 3
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824