apiVersion: v1
kind: Pod
metadata:
  labels:
    app: ubuntu-kafka
  name: ubuntu-kafka
  namespace: kafka
spec:
  containers:
  - command:
    - sleep
    - "604800"
    image: python:3.11.4-bullseye
    imagePullPolicy: IfNotPresent
    name: ubuntu
  #   volumeMounts:
  #   - mountPath: /var/data
  #     name: data
  # volumes:
  # - name: data
  #   persistentVolumeClaim:
  #     claimName: data0-kafka-2
