apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-tls-client
  namespace: confluent
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: ubuntu-tls-kafka
  name: ubuntu-tls-kafka
  namespace: confluent
spec:
  containers:
  - command:
    - sleep
    - "604800"
    image: ubuntu:focal
    imagePullPolicy: IfNotPresent
    name: ubuntu
    volumeMounts:
    - mountPath: /var/tls
      name: tls
  volumes:
  - name: tls
    persistentVolumeClaim:
      claimName: kafka-tls-client
